### ISSUE TITLE
Window with list of servers not opening

### ISSUE THREAD

**Issue by Kruk79** [morpheusthewhite/nordpy#25]
**Describe the bug**
After providing the password the window with list of servers is not appearing.

**To Reproduce**
1. Go to '...' - start / system tools / select nordpy
2. Provide password and press ok
3. Error - window with servers is not appearing

**Expected behavior**
As previously window with servers should appear

**Desktop (please complete the following information):**
 - Linux Distribution
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

 - NordPy version (`git log --pretty=format:'%H' -n 1`) 1.3

**Additional context**
My Raspbian was updated and I believe some of the settings/files/folders have been changed or removed. I'm not experienced with Linux so not sure how to fix it. Apologies for another issues raised.

Info after reinstall:

pi@raspberrypi:~ $ sudo /home/pi/NordPy-1.3/install.sh
Do you want to install support for obfuscated servers (it will reinstall openvpn)?[y/n] (Recommended: n)
n
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  openvpn-systemd-resolved
The following NEW packages will be installed:
  openvpn
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/426 kB of archives.
After this operation, 1,019 kB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package openvpn.
(Reading database ... 106240 files and directories currently installed.)
Preparing to unpack .../openvpn_2.4.7-1_armhf.deb ...
Unpacking openvpn (2.4.7-1) ...
Setting up openvpn (2.4.7-1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for systemd (241-7~deb10u1+rpi1) ...
Required packages installed
/home/pi/NordPy-1.3/install.sh: line 69: nmcli: command not found
/home/pi/NordPy-1.3/install.sh: line 69: [: =: unary operator expected
installing certificates (needed by ipsec)
ln: failed to create symbolic link '/usr/local/bin/nordpy': File exists
downloading and extracting conf files from NordVPN

Info from running nordpy.py

pi@raspberrypi:~/NordPy-1.3 $ ./nordpy.py
Traceback (most recent call last):
  File "./nordpy.py", line 28, in <module>
    main()
  File "./nordpy.py", line 23, in main
    app = gui()
  File "/home/pi/NordPy-1.3/bin/gui.py", line 46, in __init__
    running_vpn = get_running_vpn()
  File "/home/pi/NordPy-1.3/bin/vpn_util/vpn.py", line 57, in get_running_vpn
    if nm_running_vpn():
  File "/home/pi/NordPy-1.3/bin/vpn_util/nm.py", line 136, in nm_running_vpn
    list_process = subprocess.Popen(args, universal_newlines=True, stdout=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nmcli': 'nmcli'
Retrieved stats
Retrieved stats

**Comment by morpheusthewhite** [comment]
Try reinstalling nordpy, it should work now

**Comment by Kruk79** [comment]
Thanks. You are great. It is working now however still getting the below during install:

/home/pi/NordPy-1.3/install.sh: line 69: nmcli: command not found
/home/pi/NordPy-1.3/install.sh: line 69: [: =: unary operator expected
installing certificates (needed by ipsec)
ln: failed to create symbolic link '/usr/local/bin/nordpy': File exists

but it works.

**Comment by morpheusthewhite** [comment]
Yeah, don't worry for them, I expected them (I'll fix them soon too, they aren't real errors)

**Comment by sorryusernameisalreadytaken** [comment]
> 
> 
> Yeah, don't worry for them, I expected them (I'll fix them soon too, they aren't real errors)

It would be awesome when you can make a release of this fix so AUR get this fix too.

**Comment by morpheusthewhite** [comment]
> It would be awesome when you can make a release of this fix so AUR get this fix too.

Done!
