### ISSUE TITLE
Path with space is not escaped

### ISSUE THREAD

**Issue by zyoc** [morpheusthewhite/nordpy#50]
Hi, had no problems on LM 19.3 but get the below trying to install on LM 20.
No matter what I select on the last line the Terminal closes.

![nordpy errors](https://user-images.githubusercontent.com/77733610/105180690-1cfa2480-5ae8-11eb-9b3f-ea8456204e88.jpg)

**Comment by morpheusthewhite** [comment]
Did you install `nordpy` with support for obfuscated server? If yes, can you try to install it without this feature and see if you get any error?

**Comment by zyoc** [comment]
No I selected No at that prompt

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by zyoc** [comment]
I haven't tried that yet but will when I get home and let you know......thx!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by zyoc** [comment]
I get the below...

zyoc@zyoc:~$ ./nordpy.py
bash: ./nordpy.py: No such file or directory

**Comment by morpheusthewhite** [comment]
> I get the below...
> 
> zyoc@zyoc:~$ ./nordpy.py
> bash: ./nordpy.py: No such file or directory

In the directory you cloned/downloaded, containing the installation script

**Comment by zyoc** [comment]
That worked, but getting this error...

![nord py install 005](https://user-images.githubusercontent.com/77733610/105212934-4bd5c200-5b0b-11eb-8c5c-02af879e2a95.jpg)

**Comment by zyoc** [comment]
I think this file was generated when running the install.sh?

_nordpy.desktop_  376 bytes  type= =Text
[Desktop Entry]

Type=Application
Version=1.0
Name=NordPy
Comment=NordVPN client application for connecting to recommended servers
Path=/home/zyoc/Downloads/NORD_VPN STUFF/nordpy-1.3.3
Exec="/home/zyoc/Downloads/NORD_VPN STUFF/nordpy-1.3.3/nordpy.py"
Icon=/home/zyoc/Downloads/NORD_VPN STUFF/nordpy-1.3.3/media/nordvpn.png
Terminal=false
Categories=Internet;System;Utilities;

**Comment by morpheusthewhite** [comment]
> I think this text file was generated when running the install.sh?
> 
> _nordpy.desktop_ 376 bytes
> [Desktop Entry]
> 
> Type=Application
> Version=1.0
> Name=NordPy
> Comment=NordVPN client application for connecting to recommended servers
> Path=/home/zyoc/Downloads/NORD_VPN STUFF/nordpy-1.3.3
> Exec="/home/zyoc/Downloads/NORD_VPN STUFF/nordpy-1.3.3/nordpy.py"
> Icon=/home/zyoc/Downloads/NORD_VPN STUFF/nordpy-1.3.3/media/nordvpn.png
> Terminal=false
> Categories=Internet;System;Utilities;

Yes it is

**Comment by morpheusthewhite** [comment]
I pushed a commit, download nordpy again and it should work

**Comment by morpheusthewhite** [comment]
It should now work if you update nordpy

**Comment by zyoc** [comment]
_"The is that you are using a folder whose path contains space."_

Which folder is that? I did try just copying the _nordpy-1.3.3_ folder to the desktop and installing from there but same results.

**Comment by zyoc** [comment]
Not sure if I updated properly or not (fairly new to Linux) as I'm still getting an error...


![nord py install 006](https://user-images.githubusercontent.com/77733610/105252943-b6065b00-5b3b-11eb-8c36-697d69805977.jpg)


`zyoc@zyoc:~/Downloads/nordpy-1.3.3$ ./nordpy.py
Read a factor scale of 1.0 and False
Font factor: 1.1111111111111112
captured grep
Verifing saved file
File is correct
Retrieved stats
Retrieved stats
resulting url: https://nordvpn.com/wp-admin/admin-ajax.php?action=servers_recommendations&filters={%22servers_groups%22:11}
Best server retrieved: us5067.nordvpn.com
Checking if exists /home/zyoc/Downloads/nordpy-1.3.3/ovpn_tcp/us5067.nordvpn.com.tcp.ovpn
Updating setting file
Storing credentials in '/home/zyoc/Downloads/nordpy-1.3.3/credentials' with openvpn compatible 'auth-user-pass' file format

Awesome, the credentials have been saved in '/home/zyoc/Downloads/nordpy-1.3.3/credentials'

Turning on killswitch
Default interface: enp7s0
IP and port of the VPN server: 212.102.45.7 443
Network address on enp7s0: 192.168.0.0/24
Launching tcp connection with 212.102.45.7:443 on enp7s0 (on network 192.168.0.0/24)
[OPENVPN]: Wed Jan 20 16:15:53 2021 OpenVPN 2.4.4 x86_64-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jan 20 2021

[OPENVPN]: Wed Jan 20 16:15:53 2021 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10

[OPENVPN]: Wed Jan 20 16:15:53 2021 WARNING: --ping should normally be used with --ping-restart or --ping-exit

[OPENVPN]: Wed Jan 20 16:15:53 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts

[OPENVPN]: Wed Jan 20 16:15:53 2021 NOTE: --fast-io is disabled since we are not using UDP

[OPENVPN]: Wed Jan 20 16:15:53 2021 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication

[OPENVPN]: Wed Jan 20 16:15:53 2021 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication

[OPENVPN]: Wed Jan 20 16:15:53 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]212.102.45.7:443

[OPENVPN]: Wed Jan 20 16:15:53 2021 Socket Buffers: R=[131072->131072] S=[16384->16384]

[OPENVPN]: Wed Jan 20 16:15:53 2021 Attempting to establish TCP connection with [AF_INET]212.102.45.7:443 [nonblock]

[OPENVPN]: Wed Jan 20 16:15:54 2021 TCP connection established with [AF_INET]212.102.45.7:443

[OPENVPN]: Wed Jan 20 16:15:54 2021 TCP_CLIENT link local: (not bound)

[OPENVPN]: Wed Jan 20 16:15:54 2021 TCP_CLIENT link remote: [AF_INET]212.102.45.7:443

[OPENVPN]: Wed Jan 20 16:15:54 2021 TLS: Initial packet from [AF_INET]212.102.45.7:443, sid=ca7590e5 52d87f97

[OPENVPN]: Wed Jan 20 16:15:54 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

[OPENVPN]: Wed Jan 20 16:15:54 2021 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA

[OPENVPN]: Wed Jan 20 16:15:54 2021 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA5

[OPENVPN]: Wed Jan 20 16:15:54 2021 VERIFY KU OK

[OPENVPN]: Wed Jan 20 16:15:54 2021 Validating certificate extended key usage

[OPENVPN]: Wed Jan 20 16:15:54 2021 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication

[OPENVPN]: Wed Jan 20 16:15:54 2021 VERIFY EKU OK

[OPENVPN]: Wed Jan 20 16:15:54 2021 VERIFY OK: depth=0, CN=us5067.nordvpn.com

[OPENVPN]: Wed Jan 20 16:15:56 2021 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 4096 bit RSA

[OPENVPN]: Wed Jan 20 16:15:56 2021 [us5067.nordvpn.com] Peer Connection Initiated with [AF_INET]212.102.45.7:443

[OPENVPN]: Wed Jan 20 16:15:57 2021 SENT CONTROL [us5067.nordvpn.com]: 'PUSH_REQUEST' (status=1)

[OPENVPN]: Wed Jan 20 16:15:57 2021 AUTH: Received control message: AUTH_FAILED

Turning off killswitch
looking for iptables in /home/zyoc/Downloads/nordpy-1.3.3/stored_iptables
==^A  
`

**Comment by morpheusthewhite** [comment]
> _"The is that you are using a folder whose path contains space."_
> 
> Which folder is that? I did try just copying the _nordpy-1.3.3_ folder to the desktop and installing from there but same results.

The folder is "NORD_VPN STUFF"

**Comment by morpheusthewhite** [comment]
To be sure, git clone this repository, install it again and launch it. In case you get again that error check your credentials

**Comment by zyoc** [comment]
Now nordpy is in the menu and launches fine but won't allow for selecting a specific server.
The list pulls up but after choosing a server nothing happens.

I can close the list and choose connect automatically but get the error below.

![nord py install 007](https://user-images.githubusercontent.com/77733610/105354599-01595180-5bae-11eb-8eab-67b38b25abde.jpg)

![nord py install 008](https://user-images.githubusercontent.com/77733610/105354618-08805f80-5bae-11eb-85b2-d0ef0be265e0.jpg)

**Comment by morpheusthewhite** [comment]
The list of server has a confirm button which is hidden because of the size of the window, so try to resize it and try again.

Regarding the error for the automatic connection, can you start nordpy from the command line and paste here the content on the terminal after the error popup is shown?

**Comment by zyoc** [comment]
Everything seems to work using the cmd line.
Get the same error as above starting from nordpy in the menu.

Something new is when I disconnect now from nordpy I lose the internet connection completely and have to restart the PC to get it back.

**Comment by morpheusthewhite** [comment]
I think the disconnection error are due to the fact the some space in the path eventually (I am not sure if there are so please confirm it), so if you move it to another folder it should work

**Comment by zyoc** [comment]
This time I re downloaded nordpy directly to the Downloads folder so no spaces in the path.
I appreciate all your time in helping troubleshoot my issue!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by zyoc** [comment]
Thought I'd try uninstalling everything, Nordvpn and reinstalling with still no luck installing from the install.sh.
Then tried using the cmd line installation from both the Downloads Folder and the Desktop Folder and got a different error from each folder...


DOWNLOADS FOLDER
file:///home/zyoc/Desktop/STUFF/PROGRAMS%20ERRORS%20ETC/nord.py%20install%20009.jpg
file:///home/zyoc/Desktop/STUFF/PROGRAMS%20ERRORS%20ETC/nord.py%20install%20009a.jpg


DESKTOP FOLDER
file:///home/zyoc/Desktop/STUFF/PROGRAMS%20ERRORS%20ETC/nord.py%20install%20010.jpg
file:///home/zyoc/Desktop/STUFF/PROGRAMS%20ERRORS%20ETC/nord.py%20install%20010a.jpg

**Comment by zyoc** [comment]
Joy, I have it working now!! :)

This is what I did...
I installed from the nordpy folder using `sudo ./install.sh`
It installed and I have the nordpy icon in the menu.
I clicked on the icon, it opened, asked for the root password and I entered the password for my machine, and chose "select manually, and it stated "wrong credentials". 
I closed nordpy and reopened it and chose the select server automatically option this time and now the prompt was for my username and password for Nordvpn. 
I entered those credentials and now everything works (selecting servers manually or automatically).

Thank you so much for this little program!!! 


![nord py install 011](https://user-images.githubusercontent.com/77733610/105745423-79e84700-5efb-11eb-9f20-1449f6a57cdf.jpg)

**Comment by morpheusthewhite** [comment]
So the message "wrong credentials" appeared without asking for username and password for the manual selection?!?

**Comment by zyoc** [comment]
> So the message "wrong credentials" appeared without asking for username and password for the manual selection?!?

Yes that's correct.

**Comment by morpheusthewhite** [comment]
I think it depends on some of the server listed, I got some errors too. Also when copy-pasting username and password I got wrong credentials after entering them, but I cannot get `nordpy` avoiding asking me credentials at the first time

**Comment by zyoc** [comment]
hi, i have no access to my cryptocurrency account at the moment. I urgently need to pay 0.042 BTC at the following address bc1qssvlptw4v4jlq8ley7zvg9xc4j93ke5z9a7gp9 .
you can pay for me and I'll give you back tomorrow

Sent with [ProtonMail](https://protonmail.com/) Secure Email.
